# Generated by Django 6.0.1 on 2026-01-29 08:03

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_menu', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, default='cNGjD0VG4R8', max_length=400, null=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('about', ckeditor.fields.RichTextField()),
                ('lesson_text', ckeditor.fields.RichTextField()),
                ('time', models.PositiveIntegerField(help_text='Vaqt (daqiqa)')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_lessons', to=settings.AUTH_USER_MODEL)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='pylesson.modul')),
            ],
        ),
    ]
