# Generated by Django 6.0.1 on 2026-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modul',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
